# Generated by Django 2.1 on 2020-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Contains_docs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Contains_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Contains_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
