# Generated by Django 2.1 on 2020-01-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20200128_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Contains_docs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Contains_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Contains_video',
        ),
    ]
