# Generated by Django 3.0.3 on 2020-04-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20200412_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
